In [1]:
from whoscraped import functions

In [ ]:
import LanusStats

In [2]:
url = 'https://www.whoscored.com/Matches/1803673/Live/International-UEFA-Nations-League-B-2024-2025-England-Finland'

In [3]:
functions.get_match_passes(url)

,minute,second,half,teamId,playerId,playerName,x,y,endX,endY,outcome,isTouch
0,0,0,FirstHalf,422,255618,Glen Kamara,50.0,50.0,21.8,49.9,Successful,True
1,0,4,FirstHalf,422,64846,Lukás Hrádecky,24.6,44.2,43.4,72.2,Successful,True
2,0,6,FirstHalf,422,101113,Jere Uronen,42.2,71.4,19.5,61.4,Successful,True
3,0,9,FirstHalf,422,64846,Lukás Hrádecky,19.5,61.4,38.9,100.0,Unsuccessful,True
4,0,15,FirstHalf,345,318871,Trent Alexander-Arnold,62.5,0.0,74.5,10.6,Unsuccessful,True
...,...,...,...,...,...,...,...,...,...,...,...,...
1080,94,39,SecondHalf,345,113069,Jack Grealish,57.2,90.3,55.6,79.4,Successful,True
1081,94,45,SecondHalf,345,332325,Declan Rice,55.2,77.0,53.9,69.0,Successful,True
1082,94,48,SecondHalf,345,338497,Angel Gomes,49.9,67.2,43.7,38.6,Successful,True
1083,94,54,SecondHalf,345,374631,Marc Guéhi,55.5,27.1,56.6,42.8,Successful,True
1084,94,55,SecondHalf,345,338497,Angel Gomes,56.8,40.7,67.4,21.2,Successful,True